import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./../../globals.css";
import SessionWrapper from "@/components/SessionWrapper";
const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "@/components/ui/toaster"
import Navbar from "@/components/Navbar";
import SmoothScrolling from "@/components/SmoothScrolling";
import SidebarForUser from "@/components/SidebarForUser";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function UserLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <SidebarForUser>
      
      {children} 
        
    </SidebarForUser>
    </>
    // <html lang="en">
   
  );
}
